image: Visual Studio 2017
version: 1.0.4.{build}
configuration: Release
install:
- set NUGET_VERSION=%APPVEYOR_BUILD_VERSION%
build_script:
- ps: .\build.ps1 -Target package
test:
  assemblies:
    only:
      - 'Cake.FileHelpers\bin\Release\*.Tests.dll'
artifacts:
- path: Cake.FileHelpers\bin\Release\*.nupkg
  name: NuGet