image: Visual Studio 2017
version: 1.0.4.{build}
configuration: Release
install:
- set NUGET_VERSION=%APPVEYOR_BUILD_VERSION%
build_script:
- ps: .\build.ps1 -Target package
test_script:
- ps: .\build.ps1 -Target test
artifacts:
- path: output\*.nupkg
  name: NuGet